ALTER TYPE "DesignerStatus" ADD VALUE IF NOT EXISTS 'PENDING' BEFORE 'ACTIVE';

ALTER TYPE "AssetPurpose" ADD VALUE IF NOT EXISTS 'DESIGNER_PORTFOLIO' AFTER 'DESIGN_ORIGINAL';
ALTER TYPE "AssetPurpose" ADD VALUE IF NOT EXISTS 'DESIGNER_IDENTITY' AFTER 'DESIGNER_PORTFOLIO';
ALTER TYPE "AssetPurpose" ADD VALUE IF NOT EXISTS 'DESIGNER_SELFIE' AFTER 'DESIGNER_IDENTITY';
ALTER TYPE "AssetPurpose" ADD VALUE IF NOT EXISTS 'PUBLIC_INTAKE_ATTACHMENT' AFTER 'DESIGNER_SELFIE';
