export const permissions = {
  "design:create": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "design:read-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "design:submit-own": ["DESIGNER"],
  "design:moderate": ["MODERATOR", "ADMIN", "SUPER_ADMIN"],
  "rights:update-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "rights:enable-film-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "rights:disable-film-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "product-type:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "base-product:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "mockup-template:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "print-area:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "royalty-rule:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "film-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "delivery-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "worker-jobs:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "file:upload-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "listing:manage-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "listing:publish": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "shop:read": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "CUSTOMER", "CORPORATE_CLIENT", "MODERATOR", "PRODUCTION_STAFF", "OPERATIONS_MANAGER"],
  "cart:manage-own": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "order:manage-own": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "order:manage-all": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
  "production:manage": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "corporate-request:create": ["CORPORATE_CLIENT", "ADMIN", "SUPER_ADMIN"],
  "corporate-request:read-own": ["CORPORATE_CLIENT", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "corporate-request:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "designer-bid:create": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer-bid:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:create": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:send": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:accept-own": ["CORPORATE_CLIENT", "ADMIN", "SUPER_ADMIN"],
  "admin-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "email-templates:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "ai-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "ai:assist": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "MODERATOR", "OPERATIONS_MANAGER", "CORPORATE_CLIENT"],
  "marketplace-export:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "audit-logs:read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
} as const;

export type PermissionKey = keyof typeof permissions;
