export const permissions = {
  "design:create": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "design:read-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "design:submit-own": ["DESIGNER"],
  "design:moderate": ["MODERATOR", "ADMIN", "SUPER_ADMIN"],
  "design-workflow:retry": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "MODERATOR"],
  "rights:update-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "rights:enable-film-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "rights:disable-film-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "product-type:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "base-product:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "mockup-template:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "print-area:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "royalty-rule:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "film-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "film:quote": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN", "CORPORATE_CLIENT", "OPERATIONS_MANAGER"],
  "film:orders-read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
  "film:orders-manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "customer:film-order-create": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN", "CORPORATE_CLIENT"],
  "customer:film-orders-read": ["CUSTOMER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "designer:film-sales-read": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "delivery-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "currency:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF"],
  "finance:manage": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "finance:read": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF", "OPERATIONS_MANAGER"],
  "finance:adjust-royalties": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "finance:create-payout": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "finance:approve-payout": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "finance:mark-payout-paid": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "finance:reconcile-payments": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "designer:earnings-read": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "customer:dashboard-read": ["CUSTOMER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "customer:orders-read": ["CUSTOMER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "customer:profile-update": ["CUSTOMER", "ADMIN", "SUPER_ADMIN"],
  "customer:payment-retry": ["CUSTOMER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "customer:support-create": ["CUSTOMER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "designer:dashboard-read": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "designer:designs-read-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "designer:designs-create": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer:designs-submit": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer:designs-archive-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer:listings-read-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "designer:profile-update": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer:support-create": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "SUPPORT_STAFF"],
  "worker-jobs:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "file:upload-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "listing:manage-own": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "listing:publish": ["MODERATOR", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "shop:read": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "CUSTOMER", "CORPORATE_CLIENT", "MODERATOR", "PRODUCTION_STAFF", "OPERATIONS_MANAGER"],
  "cart:manage-own": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "order:manage-own": ["CUSTOMER", "DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "order:manage-all": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
  "production:manage": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:read": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "production:update-status": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:assign": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:download-file": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:request-file-generation": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:qc": ["PRODUCTION_STAFF", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:cancel": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "production:admin": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "corporate-request:create": ["CORPORATE_CLIENT", "ADMIN", "SUPER_ADMIN"],
  "corporate-request:read-own": ["CORPORATE_CLIENT", "DESIGNER", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "corporate-request:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "designer-bid:create": ["DESIGNER", "ADMIN", "SUPER_ADMIN"],
  "designer-bid:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:create": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:send": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "commercial-offer:accept-own": ["CORPORATE_CLIENT", "ADMIN", "SUPER_ADMIN"],
  "admin-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "email-templates:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "ai-settings:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "ai:assist": ["DESIGNER", "ADMIN", "SUPER_ADMIN", "MODERATOR", "OPERATIONS_MANAGER", "CORPORATE_CLIENT"],
  "marketplace:read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "MODERATOR", "SUPPORT_STAFF"],
  "marketplace:manage-settings": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:manage-mappings": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:create-export": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:generate-export": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:download-export": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:update-exported-listing": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "marketplace:record-external-sale": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "marketplace:convert-external-sale": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:override-price": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace:override-sku": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace-export:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "marketplace-publication:publish": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
  "external-sales:create": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "external-sales:import": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:map-items": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "external-sales:resolve-duplicates": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:convert-to-order": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:override-validation": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:cancel": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "external-sales:mark-paid": ["ADMIN", "SUPER_ADMIN", "FINANCE_STAFF"],
  "external-sales:view-raw-payload": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "printful-settings:manage": ["SUPER_ADMIN"],
  "printful-template:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "printful-catalog:sync": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "MODERATOR", "SUPPORT_STAFF"],
  "pod:manage-providers": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:sync-catalog": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:manage-product-mappings": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:manage-print-area-mappings": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:validate-global-pipeline": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "MODERATOR"],
  "pod:create-sync-record": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:retry-sync": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:view-provider-payloads": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "pod:webhooks-read": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
  "audit-logs:read": ["MODERATOR", "ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "FINANCE_STAFF", "SUPPORT_STAFF"],
  "media:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER"],
  "branding:manage": ["ADMIN", "SUPER_ADMIN"],
  "user:manage": ["ADMIN", "SUPER_ADMIN"],
  "intake:manage": ["ADMIN", "SUPER_ADMIN", "OPERATIONS_MANAGER", "SUPPORT_STAFF"],
} as const;

export type PermissionKey = keyof typeof permissions;
