export type JobType =
  | "GENERATE_PRODUCT_MOCKUPS"
  | "GENERATE_LOCAL_MOCKUPS"
  | "GENERATE_PRINTFUL_MOCKUPS"
  | "POLL_PRINTFUL_MOCKUP_TASK"
  | "CREATE_PRODUCT_LISTING_DRAFT"
  | "PUBLISH_MARKETPLACE_LISTING"
  | "SYNC_PRINTFUL_CATALOG"
  | "SYNC_POD_CATALOG"
  | "UPLOAD_POD_PROVIDER_FILE"
  | "SYNC_POD_PRODUCT_DRAFT"
  | "RETRY_FAILED_INTEGRATION"
  | "GENERATE_LISTING_IMAGE_PACK"
  | "GENERATE_FILM_PREVIEW"
  | "GENERATE_PRODUCTION_FILE"
  | "SEND_EMAIL";

export interface WorkerJob<T = Record<string, unknown>> {
  id: string;
  type: JobType;
  payload: T;
  createdAt: string;
}
