"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { useAuth } from "../../../auth/auth-provider";
import DashboardLayout from "../../dashboard-layout";

type Earnings = { pending: number; earned: number; payable: number; paid: number; reversed: number; adjustments: number; currentPayableBalance: number; entries: Array<{ id: string; amount: string | number; currency: string; status: string; entryType: string; orderId?: string | null; reason?: string | null; createdAt: string }> };
type Payout = { id: string; amount: string | number; currency: string; status: string; createdAt: string; reference?: string | null };

export default function DesignerEarningsPage() {
  const router = useRouter(); const { user, isLoading } = useAuth(); const [earnings, setEarnings] = useState<Earnings | null>(null); const [payouts, setPayouts] = useState<Payout[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const [a, b] = await Promise.all([fetch("/api/proxy/designer/earnings"), fetch("/api/proxy/designer/earnings/payouts")]); if (a.status === 401 || a.status === 403) { router.push("/auth/login"); return; } if (!a.ok) throw new Error(`Server error (${a.status})`); setEarnings(await a.json()); setPayouts(b.ok ? await b.json() : []); } catch (err) { setError(err instanceof Error ? err.message : "Failed to load earnings."); } finally { setLoading(false); } }
  useEffect(() => { if (!isLoading && user) void load(); }, [user, isLoading]);
  const currency = earnings?.entries[0]?.currency ?? payouts[0]?.currency ?? "UZS";
  return <DashboardLayout role="designer"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 18 }}><div><h1 style={{ margin: 0, fontSize: 22, color: "#1A1D2E" }}>Earnings</h1><p style={{ margin: "4px 0 0", color: "#6B7280", fontSize: 13 }}>Your royalty ledger and payout history.</p></div><button onClick={load} style={buttonStyle}><RefreshCw size={15} /> Refresh</button></div>{error ? <Alert message={error} /> : null}{loading ? <div style={panelStyle}>Loading earnings...</div> : null}{earnings ? <><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 12, marginBottom: 16 }}><Kpi label="Pending" value={money(earnings.pending, currency)} /><Kpi label="Earned" value={money(earnings.earned, currency)} /><Kpi label="Payable" value={money(earnings.payable, currency)} /><Kpi label="Paid" value={money(earnings.paid, currency)} /><Kpi label="Reversed" value={money(earnings.reversed, currency)} /><Kpi label="Adjustments" value={money(earnings.adjustments, currency)} /></div><Panel title="Recent Sales And Adjustments"><Rows entries={earnings.entries} /></Panel><Panel title="Payout History">{payouts.length === 0 ? <p style={{ color: "#6B7280", margin: 0 }}>No payouts yet.</p> : <table style={tableStyle}><thead><tr>{["Date", "Amount", "Status", "Reference"].map((h) => <th key={h} style={thStyle}>{h}</th>)}</tr></thead><tbody>{payouts.map((payout) => <tr key={payout.id} style={{ borderBottom: "1px solid #F0F2FA" }}><td style={tdStyle}>{new Date(payout.createdAt).toLocaleDateString()}</td><td style={{ ...tdStyle, fontWeight: 800 }}>{money(Number(payout.amount), payout.currency)}</td><td style={tdStyle}>{payout.status}</td><td style={tdStyle}>{payout.reference || "-"}</td></tr>)}</tbody></table>}</Panel><Link href="/dashboard/designer/settings" style={linkStyle}>Payout settings</Link></> : null}</DashboardLayout>;
}
function Rows({ entries }: { entries: Earnings["entries"] }) { return entries.length === 0 ? <p style={{ color: "#6B7280", margin: 0 }}>No royalty entries yet.</p> : <table style={tableStyle}><thead><tr>{["Date", "Type", "Status", "Amount", "Order", "Reason"].map((h) => <th key={h} style={thStyle}>{h}</th>)}</tr></thead><tbody>{entries.slice(0, 100).map((entry) => <tr key={entry.id} style={{ borderBottom: "1px solid #F0F2FA" }}><td style={tdStyle}>{new Date(entry.createdAt).toLocaleDateString()}</td><td style={tdStyle}>{entry.entryType}</td><td style={tdStyle}>{entry.status}</td><td style={{ ...tdStyle, fontWeight: 800 }}>{money(Number(entry.amount), entry.currency)}</td><td style={tdStyle}>{entry.orderId ? `#${entry.orderId.slice(-6)}` : "-"}</td><td style={tdStyle}>{entry.reason || "-"}</td></tr>)}</tbody></table>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section style={panelStyle}><h2 style={{ margin: "0 0 12px", fontSize: 15, color: "#1F2937" }}>{title}</h2>{children}</section>; }
function Kpi({ label, value }: { label: string; value: string }) { return <div style={panelStyle}><div style={{ color: "#6B7280", fontSize: 12 }}>{label}</div><div style={{ color: "#1A1D2E", fontWeight: 800, marginTop: 8 }}>{value}</div></div>; }
function Alert({ message }: { message: string }) { return <div role="alert" style={{ background: "#FEF2F2", border: "1px solid #FECACA", borderRadius: 8, padding: 14, color: "#B42318", marginBottom: 16 }}>{message}</div>; }
function money(value = 0, currency = "UZS") { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: currency === "UZS" ? 0 : 2 }).format(value || 0); }
const buttonStyle = { display: "inline-flex", alignItems: "center", gap: 8, border: "1px solid #E8EAFB", background: "white", borderRadius: 8, padding: "8px 12px", color: "#374151", cursor: "pointer" };
const panelStyle = { background: "white", border: "1px solid #E8EAFB", borderRadius: 8, padding: 14, marginBottom: 16, overflow: "auto" };
const tableStyle = { width: "100%", borderCollapse: "collapse" as const, fontSize: 13, minWidth: 760 };
const thStyle = { textAlign: "left" as const, padding: "10px 12px", color: "#6B7280", background: "#F8F9FF", borderBottom: "1px solid #E8EAFB" };
const tdStyle = { padding: "10px 12px", color: "#374151" };
const linkStyle = { color: "#788AE0", textDecoration: "none", fontWeight: 700 };
