"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, ErrorState, FormField, Input, Textarea } from "@rashpod/ui";
import { useAuth } from "../../../auth/auth-provider";
import DashboardLayout from "../../dashboard-layout";

type Profile = { email: string; displayName: string; phone?: string; defaultDeliveryAddress?: string; language?: string };

export default function CustomerProfilePage() {
  const router = useRouter(); const { user, isLoading: authLoading } = useAuth(); const [profile, setProfile] = useState<Profile>({ email: "", displayName: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { if (authLoading) return; if (!user) { router.push("/auth/login?next=/dashboard/customer/profile"); return; } const load = async () => { setLoading(true); try { const res = await fetch("/api/proxy/customer/profile"); if (!res.ok) throw new Error(`Server error (${res.status})`); setProfile(await res.json()); } catch (err) { setError(err instanceof Error ? err.message : "Failed to load profile."); } finally { setLoading(false); } }; void load(); }, [user, authLoading, router]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const res = await fetch("/api/proxy/customer/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const data = await res.json(); if (!res.ok) throw new Error(data?.message || `Server error (${res.status})`); setProfile(data); setSuccess("Profile saved."); } catch (err) { setError(err instanceof Error ? err.message : "Failed to save profile."); } finally { setSaving(false); } }
  return <DashboardLayout role="customer"><div className="mb-6"><h1 className="text-2xl font-bold text-brand-ink">Profile</h1><p className="text-sm text-brand-muted">Manage basic contact and delivery preferences.</p></div>{error ? <ErrorState title="Profile issue" description={error} /> : null}{success ? <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{success}</div> : null}<form onSubmit={submit} className="max-w-2xl rounded-2xl border border-brand-line bg-white p-5 shadow-soft"><fieldset disabled={loading || saving} className="space-y-4"><FormField label="Name"><Input value={profile.displayName || ""} onChange={(event) => setProfile({ ...profile, displayName: event.target.value })} /></FormField><FormField label="Email" helperText="Contact support to change your email."><Input value={profile.email || ""} disabled /></FormField><FormField label="Phone"><Input value={profile.phone || ""} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /></FormField><FormField label="Default delivery address"><Textarea value={profile.defaultDeliveryAddress || ""} onChange={(event) => setProfile({ ...profile, defaultDeliveryAddress: event.target.value })} /></FormField><FormField label="Language"><Input value={profile.language || "en"} onChange={(event) => setProfile({ ...profile, language: event.target.value })} /></FormField><Button type="submit" loading={saving}>Save profile</Button></fieldset></form></DashboardLayout>;
}
