"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button, ErrorState, FormField, Input, Select, Textarea } from "@rashpod/ui";
import { useAuth } from "../../../auth/auth-provider";
import DashboardLayout from "../../dashboard-layout";

type OrderSummary = { id: string; orderNumber: string; customerStatus: string; createdAt: string };
const categories = [{ value: "payment", label: "Payment" }, { value: "delivery", label: "Delivery" }, { value: "product_issue", label: "Product issue" }, { value: "cancellation_refund", label: "Cancellation/refund request" }, { value: "other", label: "Other" }];

export default function CustomerSupportPage() {
  const params = useSearchParams(); const initialOrderId = params.get("orderId") || ""; const router = useRouter(); const { user, isLoading: authLoading } = useAuth(); const [orders, setOrders] = useState<OrderSummary[]>([]); const [orderId, setOrderId] = useState(initialOrderId); const [category, setCategory] = useState("payment"); const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { if (authLoading) return; if (!user) { router.push("/auth/login?next=/dashboard/customer/support"); return; } const load = async () => { try { const res = await fetch("/api/proxy/customer/orders"); if (res.ok) { const data = await res.json(); setOrders(data); if (!initialOrderId && data[0]?.id) setOrderId(data[0].id); } } catch { /* support form can still show validation */ } }; void load(); }, [user, authLoading, router, initialOrderId]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { if (!orderId.trim()) throw new Error("Choose an order so we can attach the order reference automatically."); const res = await fetch(`/api/proxy/customer/orders/${orderId}/support-request`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, subject, message }) }); const data = await res.json(); if (!res.ok) throw new Error(data?.message || `Server error (${res.status})`); setSuccess("Support request sent. RashPOD support will review it."); setMessage(""); setSubject(""); } catch (err) { setError(err instanceof Error ? err.message : "Failed to send support request."); } finally { setSaving(false); } }
  return <DashboardLayout role="customer"><div className="mb-6"><h1 className="text-2xl font-bold text-brand-ink">Contact Support</h1><p className="text-sm text-brand-muted">Send a support request connected to one of your orders.</p></div>{error ? <ErrorState title="Support request issue" description={error} /> : null}{success ? <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{success}</div> : null}<form onSubmit={submit} className="max-w-2xl rounded-2xl border border-brand-line bg-white p-5 shadow-soft"><div className="space-y-4"><FormField label="Order"><Select value={orderId} onChange={(event) => setOrderId(event.target.value)}><option value="">Choose an order</option>{orders.map((order) => <option key={order.id} value={order.id}>#{order.orderNumber} · {order.customerStatus} · {new Date(order.createdAt).toLocaleDateString()}</option>)}</Select></FormField><FormField label="Category"><Select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select></FormField><FormField label="Subject"><Input value={subject} onChange={(event) => setSubject(event.target.value)} /></FormField><FormField label="Message"><Textarea required value={message} onChange={(event) => setMessage(event.target.value)} /></FormField><Button type="submit" loading={saving} disabled={!orderId}>Send request</Button></div></form></DashboardLayout>;
}
